name: Java CI with Gradle

on:
  push:
    branches: [ master ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Auth with google
        uses: 'google-github-actions/auth@v0'
        with:
          service_account: 'github-trevorism-testing@trevorism-testing.iam.gserviceaccount.com'
          workload_identity_provider: 'projects/729203316942/locations/global/workloadIdentityPools/github-trevorism-testing-pool/providers/ghism-testing-provider'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: clean build appengineStage

      - name: 'Deploy to App Engine'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          working_directory: "build/staged-app"
          deliverables: 'app.yaml'
          promote: true
          version: '0-6-0'



